version: '3.5'
services:
  crashes-prediction:
    container_name: crashes-prediction
    build: .
    ports:
     - 6060:5000
    restart: always
    volumes:
      - /home/kclo/Notebooks:/data
        # deploy:
        # resources:
        # limits:
        # memory: 4G
